/**
 * FlowLogic Setup Script
 * Run this script to quickly set up your environment variables
 * Usage: node setup.js
 */

import { writeFileSync, existsSync } from 'fs';
import { createInterface } from 'readline';

const rl = createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setup() {
  console.log('\n🚀 FlowLogic Setup Script\n');
  console.log('This script will help you set up your Supabase credentials.\n');
  console.log('You can find these in your Supabase project:');
  console.log('  → Go to: https://app.supabase.com/project/_/settings/api\n');
  
  // Check if .env already exists
  if (existsSync('.env')) {
    const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  // Get Supabase URL
  const supabaseUrl = await question('📋 Enter your Supabase Project URL: ');
  if (!supabaseUrl.trim()) {
    console.log('❌ Project URL is required. Setup cancelled.');
    rl.close();
    return;
  }

  // Get Supabase Anon Key
  const supabaseKey = await question('🔑 Enter your Supabase Anon Key: ');
  if (!supabaseKey.trim()) {
    console.log('❌ Anon Key is required. Setup cancelled.');
    rl.close();
    return;
  }

  // Create .env file
  const envContent = `# Supabase Configuration
# Auto-generated by setup script

VITE_SUPABASE_URL=${supabaseUrl.trim()}
VITE_SUPABASE_ANON_KEY=${supabaseKey.trim()}

# Never commit this file to version control!
`;

  try {
    writeFileSync('.env', envContent);
    console.log('\n✅ .env file created successfully!\n');
    console.log('📝 Next steps:');
    console.log('   1. Go to your Supabase dashboard SQL Editor');
    console.log('   2. Copy and run the SQL script from SUPABASE_SETUP.md');
    console.log('   3. Enable Email authentication in Authentication → Providers');
    console.log('   4. Run: npm run dev\n');
    console.log('🎉 Setup complete! You can now start using FlowLogic with authentication.\n');
  } catch (error) {
    console.error('❌ Error creating .env file:', error.message);
  }

  rl.close();
}

setup();
