export default function SystemBadge({ type = "loading", toolUsed = null }) {
  if (type === "loading") {
    return (
      <div className="flex items-center gap-2 px-3 py-1.5 mb-3 bg-slate-900 border border-slate-700 w-fit animate-sympy-pulse shadow-sm">
        <span className="text-[13px] animate-sympy-bolt text-slate-300">⚡</span>
        <span className="text-[11px] font-mono text-slate-400 tracking-wide uppercase">
          Validating via SymPy engine...
        </span>
      </div>
    );
  }

  if (type === "verified" && toolUsed) {
    // The trust moat: this step was checked by a deterministic engine, not
    // guessed by the LLM. Make it confident and unmissable (emerald + check).
    return (
      <div
        className="group flex items-center gap-1.5 px-2.5 py-1 mt-1.5 bg-emerald-950/40 border border-emerald-700/50 w-fit shadow-sm"
        title="This step was verified by the deterministic SymPy engine — not generated by the AI. subgrad never hands you an unverified mathematical claim."
      >
        <span className="text-[11px] text-emerald-400 leading-none">✓</span>
        <span className="text-[10px] font-mono text-emerald-300 uppercase tracking-wide">
          Verified by {toolUsed}
        </span>
      </div>
    );
  }

  return null;
}
