import { isValidElement, cloneElement } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import remarkGfm from 'remark-gfm';
import { notationDictionary } from '../lib/notationDictionary';
import { NotationTooltip } from '../components/UI/NotationTooltip';
import { useSharedOptimizerStore } from '../store/optimizerStore';
import { useDataSandboxStore } from '../store/dataSandboxStore';

const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));
const executedActions = new Set();

// Build a fast lookup map for term matching
const lookupMap = {};
Object.entries(notationDictionary).forEach(([key, data]) => {
  lookupMap[data.name.toLowerCase()] = key;
  // We also map the exact symbol
  lookupMap[data.symbol.toLowerCase()] = key;
});

// Create an array of term strings sorted by length descending.
// This prevents partial matches (e.g., matching "L2" inside "L2 Regularization").
const termStrings = Object.keys(lookupMap).sort((a, b) => b.length - a.length);

const escapeRegExp = (string) => string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// Construct the Regex string. We use word boundaries \b for alphanumeric terms
// to ensure we don't match "sum" inside "assume". We don't use \b for symbols like ∇.
const termRegexParts = termStrings.map(term => {
  const isWord = /^\w+$/.test(term.replace(/\s+/g, ''));
  const escaped = escapeRegExp(term);
  return isWord ? `\\b${escaped}\\b` : escaped;
});

// The final Regex matches any dictionary term (case-insensitive)
const termsRegex = new RegExp(`(${termRegexParts.join('|')})`, 'gi');

/**
 * Replaces dictionary terms with <NotationTooltip> and parses/executes LLM action commands.
 */
function replaceTermsInString(text) {
  if (!text) return [];
  
  // Split by action regex. Capture groups are included in the split array.
  // Format: [text, actionCommand, actionValue, text, actionCommand, actionValue, ...]
  const actionParts = text.split(/\[ACTION:\s*([A-Z_]+)(?:=([^\]]+))?\]/g);
  const nodes = [];
  
  for (let i = 0; i < actionParts.length; i += 3) {
    const plainText = actionParts[i];
    
    if (plainText) {
      // Process dictionary terms within the plain text chunk
      const termParts = plainText.split(termsRegex);
      termParts.forEach((part, index) => {
        if (!part) return;
        const lowerPart = part.toLowerCase();
        if (lookupMap[lowerPart]) {
          const termKey = lookupMap[lowerPart];
          nodes.push(
            <NotationTooltip key={`${termKey}-${i}-${index}`} termKey={termKey}>
              {part}
            </NotationTooltip>
          );
        } else {
          nodes.push(part);
        }
      });
    }

    // Process the Action Command if we haven't reached the end
    if (i + 1 < actionParts.length) {
      const actionCommand = actionParts[i + 1];
      const actionValue = actionParts[i + 2];
      
      // Generate a semi-unique ID for this action relative to this text node
      const actionId = `action-${actionCommand}-${actionValue || 'none'}-${text.substring(0, 20)}`;
      
      if (!executedActions.has(actionId)) {
        executedActions.add(actionId);
        
        // Execute the Action Choreography out-of-band to prevent render loops.
        // We use an async IIFE inside the setTimeout to sequentially orchestrate the cinematic UI morphs.
        setTimeout(async () => {
          if (actionCommand === 'HIGHLIGHT_OUTLIER') {
            // a) Dispatch view change
            useSharedOptimizerStore.getState().setLabView('sandbox');
            // b) Wait for the morph animation to finish
            await sleep(500);
            // c) Trigger the target pulse
            useDataSandboxStore.getState().highlightWorstOutlier();
          } 
          else if (actionCommand === 'CRANK_LR') {
            const optimizerStore = useSharedOptimizerStore.getState();
            // a) Dispatch view change
            optimizerStore.setLabView('graph');
            // b) Wait for morph animation to finish
            await sleep(500);
            // c) Dispatch parameter change
            optimizerStore.setGraphLearningRate(5.0);
            // d) Let the user see the slider jump to the extreme value
            await sleep(400);
            // e) Fire the training simulation
            optimizerStore.startTraining();
          }
        }, 0);
      }
      
      // Crucially, we do NOT push the action tag into the nodes array,
      // which effectively hides it from the user interface.
    }
  }
  
  return nodes;
}

/**
 * Recursively walks the React AST generated by ReactMarkdown.
 * This guarantees we ONLY apply our regex to actual text nodes, completely
 * preventing accidental replacements inside code blocks or KaTeX math blocks.
 */
function processReactNodes(node) {
  if (typeof node === 'string') {
    return replaceTermsInString(node);
  }
  
  if (Array.isArray(node)) {
    return node.map((n, i) => {
      const processed = processReactNodes(n);
      return isValidElement(processed) 
        ? cloneElement(processed, { key: i }) 
        : processed;
    });
  }
  
  if (isValidElement(node)) {
    // CRITICAL GUARDRAIL: Do not traverse into code blocks or pre-formatted text
    if (node.type === 'code' || node.type === 'pre') {
      return node;
    }
    
    // CRITICAL GUARDRAIL: Do not traverse into KaTeX rendered math blocks
    if (node.props?.className && typeof node.props.className === 'string' && node.props.className.includes('math')) {
      return node;
    }
    
    // Recurse into children
    if (node.props?.children) {
      return cloneElement(node, {
        children: processReactNodes(node.props.children)
      });
    }
  }
  
  return node;
}

/**
 * Robust utility function that takes a raw markdown/text string and returns
 * a React node array where matched terms are swapped out for tooltips.
 */
export function parseMessageWithTooltips(messageText) {
  if (!messageText) return [];

  // Instead of a brittle string-level regex that tries to guess code block boundaries,
  // we leverage ReactMarkdown to parse the AST natively, then walk the AST to safely
  // swap out standard text nodes with <NotationTooltip> components.
  // We return this as an array of React Nodes to satisfy the architecture requirement.
  return [
    <ReactMarkdown
      key="markdown-root"
      remarkPlugins={[remarkMath, remarkGfm]}
      rehypePlugins={[rehypeKatex]}
      components={{
        // Intercept standard text-containing elements to process their children
        p: ({ node, children, ...props }) => <div className="mb-4" {...props}>{processReactNodes(children)}</div>,
        li: ({ node, children, ...props }) => <li {...props}>{processReactNodes(children)}</li>,
        span: ({ node, children, ...props }) => {
          if (props.className?.includes('math')) {
            return <span {...props}>{children}</span>; // Bypass KaTeX nodes
          }
          return <span {...props}>{processReactNodes(children)}</span>;
        },
        td: ({ node, children, ...props }) => <td {...props}>{processReactNodes(children)}</td>,
        th: ({ node, children, ...props }) => <th {...props}>{processReactNodes(children)}</th>,
        strong: ({ node, children, ...props }) => <strong {...props}>{processReactNodes(children)}</strong>,
        em: ({ node, children, ...props }) => <em {...props}>{processReactNodes(children)}</em>,
        // We explicitly do NOT override `code` or `pre`, keeping them pure.
      }}
    >
      {messageText}
    </ReactMarkdown>
  ];
}
